(part "3-1734577-4"
    (packageRef "317345774")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
        (port "5" (symbPinId 5) (portName "5") (portType INOUT))
        (port "6" (symbPinId 6) (portName "6") (portType INOUT))
        (port "7" (symbPinId 7) (portName "7") (portType INOUT))
        (port "8" (symbPinId 8) (portName "8") (portType INOUT))
        (port "9" (symbPinId 9) (portName "MH1") (portType INOUT))
        (port "10" (symbPinId 10) (portName "MH2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "571-3-1734577-4")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/TE-Connectivity-AMP/3-1734577-4?qs=Z4JOKa0a9TUSCOA052xCCw%3D%3D")
    (property "Manufacturer_Name" "TE Connectivity")
    (property "Manufacturer_Part_Number" "3-1734577-4")
    (property "Description" "RJ45 Connector, Single Port, 1 x 1, Standard Connector Contact Density, Jack, Shielded, Cat 3, Standard - Latch Down, 8 Position, Standard Profile ")
    (property "Datasheet_Link" "https://www.te.com/commerce/DocumentDelivery/DDEController?Action=showdoc&DocId=Customer+Drawing%7F1734577%7FD1%7Fpdf%7FEnglish%7FENG_CD_1734577_D1.pdf%7F3-1734577-4")
    (property "symbolName1" "3-1734577-4")
)
